### ISSUE TITLE
Unable to run update tests

### ISSUE THREAD

**Issue by MarisBogdan** [mozilla/iris_firefox#3498] opened 2019-07-22 15:37 UTC
We are trying to run update tests with iris but we are unable to:

Running `run_update_suite.sh --builds=64.0b10_fr,65.0b3_de,66.0b4_en-US --channel=beta` resulted in: 
![capture](https://user-images.githubusercontent.com/12394562/61645630-b3f5de80-acaf-11e9-9708-0297c3bfc2d6.jpg)

Is it possible that the command for running update tests changed?

**Comment by tracywalker** [comment] 2019-07-22 15:44
It looks like iris is not obeying the `-o` argument (override disabled tests) from run_update_suite.sh.

**Comment by mwobensmith** [comment] 2019-07-23 17:09
This will be fixed when you get core code later this week. The issue is with the `-t` flag. Somehow we lost the ability to use the comma to pass in multiple test params. I fixed this, as well as the `-x` exclude flag.

**Comment by tracywalker** [comment] 2019-08-06 13:42
This is fixed, However, more issues have arisen and there is still work to be done on run_update_suite.sh. I expect I be fully done with the work on that script and the tests that it supports by next week.

However, you may run update tests directly from the command line to execute them one by one.

**Closed by tracywalker** 2019-08-06 13:42 UTC
Labels: bug, core, regression
