### ISSUE TITLE
Iris doesn't close Firefox windows

### ISSUE THREAD

**Issue by nevdokimov** [mozilla/iris_firefox#3231] opened 2019-06-10 09:55 UTC
Results of nightly runs shows that sometimes Iris cannot close Firefox windows with test cases which are stuck with some fails. 
It opens lots of windows of different test cases and then it doesn't work at all. And it also doesn't close already opened windows.

It's complicated to investigate this problem due to the next issue: 
https://github.com/mozilla/iris/issues/438

**Comment by mwobensmith** [comment] 2019-06-10 15:13
The issue is that tests that invoke `select_tab(num)` cause the Windows home menu to appear, and then trigger a `KeyError`. Then the browser is orphaned. Not sure why, debugging now.

**Comment by mwobensmith** [comment] 2019-06-11 01:16
Easily fixed by converting argument of type `int` to a `str`. The type method expects a string, and the argument is explicitly typed in Python 3, so it throws an exception.

I'm going to do the conversion in the `select_tab` method itself.

**Comment by mwobensmith** [comment] 2019-06-11 01:31
This should be fixed now.

**Closed by mwobensmith** 2019-06-11 01:31 UTC

**Comment by mwobensmith** [comment] 2019-06-11 03:30
I see this might still be happening in some of the download manager tests. We'll address this in a different fix.

**Comment by nevdokimov** [comment] 2019-06-11 07:42
Yes, I noticed this problem for some of the download manager tests.
Okay, I got it. Thank you.
