### ISSUE TITLE
"Screenshot failed" occurring during the nightly runs resulting the whole run failed

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris_firefox#4126] opened 2019-10-29 10:11 UTC
"Screenshot failed" occurring during the nightly runs on the Linux and Windows.
As result there is no json file and the whole run is corrupted.
See logs in attachments.
[iris_log_linux.log](https://github.com/mozilla/iris_firefox/files/3782938/iris_log.5.log)
[iris_log_win10.log](https://github.com/mozilla/iris_firefox/files/3782934/iris_log.log)

**Comment by mwobensmith** [comment] 2019-10-29 20:50
Tracking in core.

https://github.com/mozilla/iris/issues/635

**Comment by tracywalker** [comment] 2019-10-29 22:08
We're going to create a branch from this issue with a potential fix in core iris version 0.8.1.  Please try this in next daily test runs.

**Comment by spronoza** [comment] 2019-10-31 13:06
Still failing on Linux. See run log from branch issue_4126
[iris_log.log](https://github.com/mozilla/iris_firefox/files/3793846/iris_log.20.log)

**Comment by mwobensmith** [comment] 2019-10-31 21:56
@spronoza This fixed the issues on Windows, yes?

**Comment by mwobensmith** [comment] 2019-10-31 23:03
I just noticed, by looking at that [last Linux log file](https://github.com/mozilla/iris_firefox/files/3793846/iris_log.20.log), that this run has a very large amount of test failures before the screenshots fail. Talking to @tracywalker he thinks the failures are likely caused by issues #3962 and #4093. I don't know if those have been fixed on Windows (and not Linux) but I have a theory as to why we are seeing the screenshot error.

Each failing test is run three times, generating three times the amount of debug images. I believe this is exhausting memory and/or disk space. To test this theory, rerun with `-m 1` and see if it gets through the entire run.

**Comment by tracywalker** [comment] 2019-10-31 23:27
I'm sorry Matt.  #3962 was for the nightly target only.

**Comment by mwobensmith** [comment] 2019-11-01 18:37
@tracywalker No worries. 

Main question still stands though - have the errors improved? If not, can we try the above suggestion to see if it helps?

**Comment by tracywalker** [comment] 2019-11-08 15:58
From or weekly meeting this didn't seem to help on Linux.

**Comment by mwobensmith** [comment] 2019-11-12 20:46
Another thing to try - if you see that the run is failing due to a large amount of errors, restart the run and use the `-y` flag. This is the "Treeherder mode" and it will turn off debug image generation for the run. This would be a way to save the run if this problem is memory- or disk-related, which I think it could be.

**Closed** 2022-02-24 18:05 UTC
Labels: bug, ARCHIVED
